#! /usr/bin/env python3
from os import environ, makedirs
import re

target = environ.get("TARGET")
if not target:
    print("::error ::TARGET is required but missing")
    exit(1)

release_tag = environ.get("RELEASE_TAG")
if not release_tag:
    print("::error ::RELEASE_TAG is required but missing")
    exit(1)

checksum = None
word_splitter = re.compile(r"\s+")
with open("checksums/sha256sum.txt", "r") as file:
    for line in file.readlines():
        line = line.strip()
        if line.endswith(target):
            checksum, _ = word_splitter.split(line)

maintainer = "# Maintainer: Da4ndo <contact@da4ndo.com>\n"
opening = maintainer + "\n# This file is automatically generated. Do not edit.\n"

print("Generating PKGBUILD for Hyde-Ext-git...")
makedirs("./pkgbuild/Hyde-Ext-git", exist_ok=True)
with open("./pkgbuild/Hyde-Ext-git/PKGBUILD", "w") as pkgbuild:
    content = opening + "\n"
    content += "pkgname=hyde-ext-git\n"
    content += f"pkgver={release_tag}\n"
    source_url = f"https://github.com/Da4ndo/Hyde-Ext/archive/{release_tag}.tar.gz"
    content += f"source=(Hyde-Ext-{release_tag}.tar.gz::{source_url})\n"
    content += "sha256sums=(SKIP)\n"
    with open("./template/Hyde-Ext-git/PKGBUILD", "r") as template_file:
        content += template_file.read() + "\n"
    pkgbuild.write(content)

print("Generating PKGBUILD for Hyde-Ext...")
makedirs("./pkgbuild/Hyde-Ext", exist_ok=True)
with open("./pkgbuild/Hyde-Ext/PKGBUILD", "w") as pkgbuild:
    content = opening + "\n"
    content += "pkgname=hyde-ext\n"
    content += f"pkgver={release_tag}\n"
    source_url_prefix = (
        f"https://github.com/Da4ndo/Hyde-Ext/releases/download/{release_tag}"
    )
    source_url = f"{source_url_prefix}/Hyde-Ext-{target}"

    content += f"source=(Hyde-Ext-{checksum}::{source_url})\n"
    content += f"_checksum={checksum}\n"

    with open("./template/Hyde-Ext/PKGBUILD", "r") as template_file:
        content += template_file.read() + "\n"
    pkgbuild.write(content)
