name: Deploy to AUR and GitHub Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/hyde-ext
        asset_name: hyde-ext
        asset_content_type: application/octet-stream

  deploy_aur:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get release version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Update PKGBUILD
      run: |
        sed -i "s/pkgver=.*/pkgver=${{ steps.get_version.outputs.VERSION }}/" template/hyde-ext/PKGBUILD
        echo "Updating PKGBUILD to version ${{ steps.get_version.outputs.VERSION }}"
        assets_url=$(curl -sL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
          jq -r '.assets[0].browser_download_url')
        echo "Assets URL: $assets_url"
        if [ -z "$assets_url" ]; then
          echo "Failed to fetch assets URL"
          exit 1
        fi
        sed -i "s|source=.*|source=(\"$assets_url\")|" template/hyde-ext/PKGBUILD
        echo "Downloading asset for SHA256 calculation"
        sha256sum=$(curl -sL "$assets_url" | sha256sum | cut -d ' ' -f 1)
        echo "SHA256: $sha256sum"
        sed -i "s/sha256sums=.*/sha256sums=('$sha256sum')/" template/hyde-ext/PKGBUILD
    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
      with:
        pkgname: hyde-ext
        pkgbuild: ./template/hyde-ext/PKGBUILD
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: "Update to version ${{ steps.get_version.outputs.VERSION }}"
        ssh_keyscan_types: rsa,ecdsa,ed25519
