name: Publish new release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout@v4
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Rust stable version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Prepare Environment Variables
      run: |
        echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
        echo "SAFE_REPO_NAME=$(echo $REPO_NAME | sed 's/\//-/g')" >> $GITHUB_ENV

    - name: Echo Variables
      run: |
        echo "Repository Name: $REPO_NAME"
        echo "Safe Repository Name: $SAFE_REPO_NAME"

    - name: Build Release
      run: |
        echo ":: Starting build process..."
        cargo build --release
        echo "  -> Build completed successfully."

    - name: Archive Release Binary
      run: |
        echo ":: Archiving release binary..."
        tar -czvf $SAFE_REPO_NAME-${{ github.ref_name }}-x86_64.tar.gz -C ./target/release/ hyde-ext
        echo "  -> Archive created successfully."
        ls

    - name: Upload Release Tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ env.SAFE_REPO_NAME }}-${{ github.ref_name }}-x86_64.tar.gz
        asset_name: ${{ env.SAFE_REPO_NAME }}-${{ github.ref_name }}-x86_64.tar.gz
        asset_content_type: application/gzip