name: Publish new release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Publish Process
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build Release
      run: |
        echo ":: Starting build process..."
        cargo build --release
        echo "  -> Build completed successfully."

    - name: Archive Release Binary
      run: |
        echo ":: Archiving release binary..."
        REPO_NAME="${{ github.repository }}"
        SAFE_REPO_NAME="${REPO_NAME/\//-}"
        tar -czvf ${SAFE_REPO_NAME}-${{ github.ref_name }}-x86_64.tar.gz  -C ./ assets -C ./target/release/ hyde-ext
        echo "  -> Archive created successfully."
        ls

    - name: Upload Gzip of Release Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${SAFE_REPO_NAME}-${{ github.ref_name }}-x86_64.tar.gz
        asset_name: ${SAFE_REPO_NAME}-${{ github.ref_name }}-x86_64.tar.gz
        asset_content_type: application/gzip